services:
  gemini-mcp-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MCP_SERVER_TOKEN=${MCP_SERVER_TOKEN}
    volumes:
      - ./certs:/app/certs:ro
    networks:
      - mcp_network

networks:
  mcp_network:
    driver: bridge
